// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWWiDyprrC6tYp0KQ6jXdQ7CJYWcRGOEM',
    appId: '1:414295645162:web:4bad89a752c93ee2333093',
    messagingSenderId: '414295645162',
    projectId: 'invoice-generator-70b83',
    authDomain: 'invoice-generator-70b83.firebaseapp.com',
    storageBucket: 'invoice-generator-70b83.appspot.com',
    measurementId: 'G-BXJNFBVMMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIjGyeZ9O6wBsGnk5j6taYr-L2G8PuNFU',
    appId: '1:414295645162:android:1d1f1dab51d410f6333093',
    messagingSenderId: '414295645162',
    projectId: 'invoice-generator-70b83',
    storageBucket: 'invoice-generator-70b83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChfgOqAQ2Fu-Cs8tqnxga4V4PW5DfsUsI',
    appId: '1:414295645162:ios:9315bb286c46dfe7333093',
    messagingSenderId: '414295645162',
    projectId: 'invoice-generator-70b83',
    storageBucket: 'invoice-generator-70b83.appspot.com',
    iosClientId: '414295645162-9uluequtil9hrgo9kcq9n2jn2c8cdiss.apps.googleusercontent.com',
    iosBundleId: 'com.example.receiptGenerator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChfgOqAQ2Fu-Cs8tqnxga4V4PW5DfsUsI',
    appId: '1:414295645162:ios:9315bb286c46dfe7333093',
    messagingSenderId: '414295645162',
    projectId: 'invoice-generator-70b83',
    storageBucket: 'invoice-generator-70b83.appspot.com',
    iosClientId: '414295645162-9uluequtil9hrgo9kcq9n2jn2c8cdiss.apps.googleusercontent.com',
    iosBundleId: 'com.example.receiptGenerator',
  );
}
